CREATE TABLE employment_logs
(
    employment_log_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(25) NOT NULL,
    employment_action VARCHAR(5) NOT NULL,
    employment_status_updtd_tmstmp TIMESTAMP,

    CONSTRAINT emplogs_valid_action CHECK ( employment_action IN ('HIRED', 'FIRED') )
);

COMMENT ON TABLE employment_logs IS 'Contains logs about every hired or fired employee';
COMMENT ON COLUMN employment_logs.employment_log_id IS 'Primary key of the table. Is generated by default';
COMMENT ON COLUMN employment_logs.employment_action IS 'Describes action upon employee. Can be ONLY HIRED or FIRED';
COMMENT ON COLUMN employment_logs.employment_status_updtd_tmstmp IS 'Timestamp of the action';
